# Generated by Django 4.0.6 on 2022-07-13 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.TextField(verbose_name='describe')),
                ('price', models.IntegerField(verbose_name='price')),
                ('count', models.PositiveIntegerField(verbose_name='month')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_start', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='start')),
                ('book_end', models.DateField(blank=True, null=True, verbose_name='end')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='active')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='total_price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='user')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.offers', verbose_name='offer')),
            ],
        ),
    ]
